services:
  mariadb:
    container_name: edu-zas-mariadb
    image: mariadb:10.4.3
    ports:
      - "3307:3306" # Exponer el puerto para acceso externo si es necesario
    environment:
      - MYSQL_ROOT_PASSWORD=cisco-class
      - MYSQL_DATABASE=EDU_ZAS
      - MYSQL_USER=dr-cisco
      - MYSQL_PASSWORD=cisco-class
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./data/mariadb:/var/lib/mysql # ← Bind mount a carpeta local
    networks:
      - edu-zas-network

  api:
    container_name: edu-zas-api
    build: ./api
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "mysql://dr-cisco:cisco-class@edu-zas-mariadb:3306/EDU_ZAS"
      PAGE_SIZE: "10"
      JWT_SECRET: "ContraseñaSegura123&"
    depends_on:
      - mariadb
    networks:
      - edu-zas-network

  client:
    container_name: edu-zas-client
    build: ./client
    args:
      VITE_API_URL: "http://edu-zas-api:3000"
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - edu-zas-network

networks:
  edu-zas-network:
    driver: bridge
