services:
  mariadb:
    container_name: edu-zas-mariadb
    image: mariadb:10.4.3
    ports:
      - "${MARIADB_HOST_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ${MARIADB_DATA_VOLUME}:/var/lib/mysql
    networks:
      - edu-zas-network

  api:
    container_name: edu-zas-api
    build: ./api
    ports:
      - "${API_HOST_PORT}:3000"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      PAGE_SIZE: "${PAGE_SIZE}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - mariadb
    networks:
      - edu-zas-network

  client:
    container_name: edu-zas-client
    build: ./client
    ports:
      - "${CLIENT_HOST_PORT}:3000"
    depends_on:
      - api
    networks:
      - edu-zas-network

networks:
  edu-zas-network:
    driver: bridge
