name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Ir a directorio del proyecto
        run: cd ${{ env.PROJECT_PATH }}

      - name: Actualizar código
        run: |
          git fetch origin production
          git reset --hard origin/production

      - name: Redeploy con Docker Compose
        run: |
          docker compose down
          docker compose build --no-cache
          docker compose up -d
